tasks:
  - init: |
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      source $HOME/.poetry/env
      poetry install
    env:
      PIP_USER: no
vscode:
  extensions:
    - "ms-python.python"
    - "ms-pyright.pyright"
    - "bungcip.better-toml"
